name: med_sarathi
description: A medical reminder app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
#  flutter_local_notifications: ^16.3.3
  flutter_local_notifications: ^17.1.2
  vibration: 3.1.3
#  awesome_notifications: ^0.10.1

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_storage: ^12.4.5
  fluttertoast: ^8.2.12
  google_sign_in: ^6.3.0
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.0
  timezone: ^0.9.0
  flutter_timezone: ^4.1.1
  permission_handler: ^11.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
